In [1]:
import pandas as pd
import numpy as np

### 1) Обоснование данных

In [3]:
data = pd.read_csv('Spotify 2010 - 2019 Top 100.csv', index_col=0)
data.head()

,artist,top genre,year released,added,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop,top year,artist type
title,,,,,,,,,,,,,,,,
STARSTRUKK (feat. Katy Perry),3OH!3,dance pop,2009.0,2022‑02‑17,140.0,81.0,61.0,-6.0,23.0,23.0,203.0,0.0,6.0,70.0,2010.0,Duo
My First Kiss (feat. Ke$ha),3OH!3,dance pop,2010.0,2022‑02‑17,138.0,89.0,68.0,-4.0,36.0,83.0,192.0,1.0,8.0,68.0,2010.0,Duo
I Need A Dollar,Aloe Blacc,pop soul,2010.0,2022‑02‑17,95.0,48.0,84.0,-7.0,9.0,96.0,243.0,20.0,3.0,72.0,2010.0,Solo
Airplanes (feat. Hayley Williams of Paramore),B.o.B,atl hip hop,2010.0,2022‑02‑17,93.0,87.0,66.0,-4.0,4.0,38.0,180.0,11.0,12.0,80.0,2010.0,Solo
Nothin' on You (feat. Bruno Mars),B.o.B,atl hip hop,2010.0,2022‑02‑17,104.0,85.0,69.0,-6.0,9.0,74.0,268.0,39.0,5.0,79.0,2010.0,Solo

<p>Этот набор данных содержит 100 лучших песен каждого года на Spotify с 2010 по 2019 год.<br>
Он позволяет нам проанализировать лучшие песни, понять какие факторы влияют на успех песни.<br>
Мы можем увидеть как менялись вкусы людей на протяжении 9 лет.<br>
Узнать самые популярные жанры и самых успешных артистов.<br>
Этот набор данных полезен для артистов, которые стремятся попасть в топ Спотифая</p>

### 2) Элементарные статистики

<p>Посмотрим какой тип данных хранится в каждом признаке</p>

In [5]:
data.dtypes

artist            object
top genre         object
year released    float64
added             object
bpm              float64
nrgy             float64
dnce             float64
dB               float64
live             float64
val              float64
dur              float64
acous            float64
spch             float64
pop              float64
top year         float64
artist type       object
dtype: object

<p>Посмотрим нет ли пропущенных значений</p>

In [6]:
data.isnull().sum()

artist           3
top genre        3
year released    3
added            3
bpm              3
nrgy             3
dnce             3
dB               3
live             3
val              3
dur              3
acous            3
spch             3
pop              3
top year         3
artist type      3
dtype: int64

<p>Удаляем пропущенные значения</p>

In [10]:
data = data.dropna()
data.isnull().sum()

artist           0
top genre        0
year released    0
added            0
bpm              0
nrgy             0
dnce             0
dB               0
live             0
val              0
dur              0
acous            0
spch             0
pop              0
top year         0
artist type      0
dtype: int64

<p>Найдем категориальные и числовые признаки (часть индивидуального задания)</p>

In [11]:
columns_numeric = data.select_dtypes(include=['float64', 'int64']).columns
columns_categorical = data.select_dtypes(include='object').columns

<p>Максимум</p>

In [12]:
data[columns_numeric].max()

year released    2021.0
bpm               206.0
nrgy               98.0
dnce               96.0
dB                 -1.0
live               83.0
val                97.0
dur               688.0
acous              98.0
spch               53.0
pop                95.0
top year         2019.0
dtype: float64

<p>Минимум</p>

In [13]:
data[columns_numeric].min()

year released    1975.0
bpm                65.0
nrgy                6.0
dnce               19.0
dB                -18.0
live                2.0
val                 4.0
dur               113.0
acous               0.0
spch                2.0
pop                35.0
top year         2010.0
dtype: float64

<p>Среднее значение</p>

In [16]:
data[columns_numeric].mean()

year released    2014.390
bpm               121.262
nrgy               69.502
dnce               66.876
dB                 -5.663
live               17.911
val                50.901
dur               220.406
acous              14.369
spch               10.064
pop                74.840
top year         2014.500
dtype: float64

<p>Медиана</p>

In [18]:
data[columns_numeric].median()

year released    2014.0
bpm               122.0
nrgy               71.0
dnce               68.0
dB                 -5.0
live               12.0
val                50.5
dur               216.0
acous               6.0
spch                6.0
pop                76.0
top year         2014.5
dtype: float64

<p>Standard deviation</p>

In [19]:
data[columns_numeric].std()

year released     3.241359
bpm              26.238022
nrgy             15.961415
dnce             13.121921
dB                2.025224
live             13.431511
val              21.563399
dur              39.927677
acous            19.454030
spch              9.276743
pop               8.807836
top year          2.873719
dtype: float64

In [20]:
data.describe(include='all')

,artist,top genre,year released,added,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop,top year,artist type
count,1000,1000,1000.000000,1000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000
unique,444,132,NaN,26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
top,Taylor Swift,dance pop,NaN,2020‑06‑22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Solo
freq,21,361,NaN,276,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,748
mean,NaN,NaN,2014.390000,NaN,121.262000,69.502000,66.876000,-5.663000,17.911000,50.901000,220.406000,14.36900,10.064000,74.840000,2014.500000,NaN
std,NaN,NaN,3.241359,NaN,26.238022,15.961415,13.121921,2.025224,13.431511,21.563399,39.927677,19.45403,9.276743,8.807836,2.873719,NaN
min,NaN,NaN,1975.000000,NaN,65.000000,6.000000,19.000000,-18.000000,2.000000,4.000000,113.000000,0.00000,2.000000,35.000000,2010.000000,NaN
25%,NaN,NaN,2012.000000,NaN,100.000000,59.000000,59.000000,-7.000000,9.000000,35.000000,197.000000,2.00000,4.000000,70.000000,2012.000000,NaN
50%,NaN,NaN,2014.000000,NaN,122.000000,71.000000,68.000000,-5.000000,12.000000,50.500000,216.000000,6.00000,6.000000,76.000000,2014.500000,NaN
75%,NaN,NaN,2017.000000,NaN,134.000000,81.250000,75.000000,-4.000000,23.000000,68.000000,237.000000,19.00000,12.000000,81.000000,2017.000000,NaN
max,NaN,NaN,2021.000000,NaN,206.000000,98.000000,96.000000,-1.000000,83.000000,97.000000,688.000000,98.00000,53.000000,95.000000,2019.000000,NaN

### 3) Распределение категориальных данных

In [21]:
for col_categorical in columns_categorical:
    print(f'{data[col_categorical].value_counts()}\n')

Taylor Swift     21
Drake            18
Calvin Harris    18
Rihanna          14
Ariana Grande    14
                 ..
Cold War Kids     1
Charli XCX        1
Bobby Shmurda     1
Becky G           1
Young Thug        1
Name: artist, Length: 444, dtype: int64

dance pop           361
pop                  57
atl hip hop          39
art pop              37
hip hop              21
                   ...
french shoegaze       1
new french touch      1
hip pop               1
australian psych      1
uk drill              1
Name: top genre, Length: 132, dtype: int64

2020‑06‑22    276
2022‑02‑17    100
2020‑06‑11    100
2020‑06‑16     99
2020‑06‑10     94
2021‑01‑28     91
2020‑06‑08     87
2020‑06‑19     85
2021‑08‑09     14
2021‑08‑17     10
2020‑08‑11      6
2021‑06‑25      6
2020‑06‑29      5
2020‑06‑25      5
2020‑08‑20      5
2021‑06‑15      5
2022‑01‑24      2
2021‑05‑06      2
2021‑09‑20      1
2021‑10‑19      1
2022‑03‑08      1
2021‑11‑25      1
2021‑03‑02      1
2021‑06‑10      1
2022‑03‑22      1
2021‑10‑28      1
Name: added, dtype: int64

Solo          748
Band/Group    169
Duo            70
Trio           13
Name: artist type, dtype: int64